core/urls.py
from django.urls import path, include

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name="index"),
    #! product
    path('products', views.product_list_view, name="products"),
    path('product/<pid>', views.product_details_view, name="product"),


    #! category
    path('categories', views.category_list_view, name="categories"),
    path('category/<cid>', views.category_product_list_view, name="category"),

    #! vendor
    path('vendors', views.vendors_list_view, name="vendors"),
    path('vendor/<vid>', views.vendor_details_view, name="vendor"),

    #! tags
    path('products/tags/<slug:tag_slug>', views.tag_list_view, name="tags"),

    #! add reviews
    path('reviews/<pid>', views.review_form_view, name="reviews"),

    #! Search by product title
    path('search/', views.search_products_view, name="search_products"),

    #! filter products by category, vendor
    path('filter_products/', views.filter_products_view, name="filter_products"),

    #! add product to cart
    path('add_to_cart', views.add_to_cart, name="add_to_cart"),

    #! cart page
    path('cart', views.cart_view, name="cart"),

    #! delete-item-from-cart
    path('delete-from-cart', views.delete_item_from_cart, name="delete-from-cart"),

    #! update cart
    path('update-cart', views.update_cart, name="update-cart"),

    #! Checkout url
    path('checkout', views.checkout_view, name="checkout"),

    #! paypal url
    path('paypal/', include('paypal.standard.ipn.urls')),

    #! payment completed url
    path('payment-completed', views.payment_completed_view, name="payment-completed"),

    #! payment failed url
    path('payment-failed', views.payment_failed_view, name="payment-failed"),

     #! dashboard url
    path('dashboard/', views.dashboard_view, name="dashboard"),

     #! order details url
    path('dashboard/order/<int:id>', views.order_detail_view, name="order-details"),

    #! making address default url
    path('make-default-address', views.make_address_default_view, name="make-default-address"),

    #! adding to wishlist url
    path('add-to-wishlist', views.add_to_wishlist_view, name="add-to-wishlist"),

    #! wishlist view url
    path('wishlist', views.wishlist_view, name="wishlist"),

    #! removing from wishlist view url
    path('remove-from-wishlist', views.remove_from_wishlist, name="remove-from-wishlist"),

    #! contact view url
    path('contact', views.contact_view, name="contact"),

    #! ajax contact view url
    path('ajax-contact-form', views.ajax_contact, name="ajax-contact-form"),

]

lexy/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userAuth.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    

    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.forms.widgets import PasswordInput, EmailInput, Textarea

from . models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write a review'}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse

from django.template.loader import render_to_string

from . models import Product, Category, Vendor, ProductImages, CartOrder, CartOrderItems, ProductReview, WishList, Address
from userAuth.models import ContactUs

from taggit.models import Tag

from django.contrib import messages #! for flash messages

from django.db.models import Avg, Count

from . forms import ProductReviewForm

from django.contrib.auth.decorators import login_required

from django.core import serializers

import calendar
from django.db.models.functions import ExtractMonth

#! for paypal
from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm

# Create your views here.

def index(request):
    #! products = Product.objects.all().order_by('-id')
    products = Product.objects.filter(product_status = "published", featured=True).order_by('id')
    categories = Category.objects.all()

    context = {
        'products': products, 'c': categories
    }
    return render(request, 'core/index.html', context)

def product_list_view(request):

    products = Product.objects.filter(product_status = "published", featured=True).order_by('id')
    categories = Category.objects.all()

    context = {
        'products': products, 'categories': categories
    }
    return render(request, 'core/product_list.html', context)

def product_details_view(request, pid):

    product = Product.objects.get(pid=pid)
    products = Product.objects.filter(category=product.category).exclude(pid=pid)[:4]

   
    reviews = ProductReview.objects.filter(product=product).order_by("-date")

    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    p_image = product.p_images.all()

    review_form = ProductReviewForm()

    make_review = True

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()

        if user_review_count > 0:
            make_review = False

    context = {
        'product': product, 'p_image': p_image, 'products': products,
        'r': reviews, 'average_rating': average_rating, 'review_form': review_form,
        'make_review': make_review,
    }

    return render(request, 'core/product_details.html', context)

def category_list_view(request):

    categories = Category.objects.all()

    context = {'categories': categories}
    return render(request, 'core/category_list.html', context)

def category_product_list_view(request, cid):

    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status = "published", category=category)

    context = {
        'category': category, 'products': products
    }

    return render(request, 'core/category_product_list.html', context)

def vendors_list_view(request):

    vendors = Vendor.objects.all()

    context = {
        'vendors': vendors
    }
    return render(request, 'core/vendors_list.html', context)

def vendor_details_view(request, vid):

    vendor = Vendor.objects.get(vid=vid)
    products = Product.objects.filter(vendor=vendor, product_status = "published")

    context = {
        'vendor': vendor, 'products': products
    }
    return render(request, 'core/vendor_details.html', context)

def tag_list_view(request, tag_slug=None):


    products = Product.objects.filter(product_status = "published").order_by("-id")

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])

    context = {
        'products': products, 'tag': tag
    }

    return render(request, 'core/tag.html', context)

def review_form_view(request, pid):
    
    product = Product.objects.get(pid=pid)
    user = request.user

    review = ProductReview.objects.create(
        user = user,
        product = product,
        review = request.POST.get('review'),
        rating = request.POST.get('rating'),
    )

    context = {
        'user': user.username,
        'review': request.POST.get('review'),
        'rating': request.POST.get('rating'),
    }

    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    return JsonResponse(
        {
            'bool': True,
            'context': context,
            'average_reviews': average_reviews,
        }
    )

def search_products_view(request):

    query = request.GET.get("q")
    products = Product.objects.filter(title__icontains=query, product_status = "published").order_by("-date")

    #? products = Product.objects.filter(title__icontains=query, description__icontains=query).order_by("-date")

    context = {
        'products': products,
        'query': query
    }
    return render(request, 'core/search_products.html', context)

def filter_products_view(request):
    categories = request.GET.getlist("category[]")
    vendors = request.GET.getlist("vendor[]")

    min_price = request.GET['min_price']
    max_price = request.GET['max_price']

    products = Product.objects.filter(product_status="published").order_by("-id").distinct()

    products = products.filter(price__gte=min_price) #! product is greater than or equal to min_price
    products = products.filter(price__lte=max_price) #! product is less than or equal to max price

    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()

    if len(vendors) > 0:
        products = products.filter(vendor__id__in=vendors).distinct()

    data = render_to_string("core/async/products_list.html", {'products': products})

    return JsonResponse({'data': data})

def add_to_cart(request):

    cart_product = {}

    cart_product[str(request.GET['id'])] = {
        'title': request.GET['title'],
        'quantity': request.GET['quantity'],
        'price': request.GET['price'],
        'image': request.GET['image'],
        'pid': request.GET['pid'],
    }

    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj'] #! get that object
            cart_data[str(request.GET['id'])]['quantity'] = int(cart_product[str(request.GET['id'])]['quantity'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_product

    return JsonResponse({
        'data': request.session['cart_data_obj'],
        'total_cart_items': len(request.session['cart_data_obj'])
    })

def cart_view(request):

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['quantity']) * float(item['price'])
        return render(request, 'core/cart.html', {'cart_data': request.session['cart_data_obj'], 'total_cart_items': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount})
    else:
        messages.warning(request, 'Your cart is empty')
        return redirect('core:index')
    
def delete_item_from_cart(request):

    product_id = str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['quantity']) * float(item['price'])

    data = render_to_string("core/async/cart-list.html", {'cart_data': request.session['cart_data_obj'], 'total_cart_items': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount})

    return JsonResponse({"data": data, "total_cart_items": len(request.session['cart_data_obj'])})
            
def update_cart(request):

    product_id = str(request.GET['id'])
    product_quantity = request.GET['quantity']
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['quantity'] = product_quantity
            request.session['cart_data_obj'] = cart_data

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['quantity']) * float(item['price'])

    data = render_to_string("core/async/cart-list.html", {'cart_data': request.session['cart_data_obj'], 'total_cart_items': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount})

    return JsonResponse({"data": data, "total_cart_items": len(request.session['cart_data_obj'])})

@login_required
def checkout_view(request):

    cart_total_amount = 0
    total_amount = 0 #! amount to send to paypal

    #! checking if cart_data_obj session exists
    if 'cart_data_obj' in request.session:
        #! getting total amount for paypal
        for p_id, item in request.session['cart_data_obj'].items():
            total_amount += int(item['quantity']) * float(item['price'])

        #! create order object
        order = CartOrder.objects.create(
            user = request.user,
            price = total_amount,
        )
        #! getting cart total amount
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['quantity']) * float(item['price'])

templates/core/cart.html
{% extends 'partials/base.html' %}

{% load static %}

{% block content %}

    <!-- Hero Section Begin -->

    <!-- Hero Section End -->

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="img/breadcrumb.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Shopping Cart</h2>
                        <div class="breadcrumb__option">
                            <a href="./index.html">Home</a>
                            <span>Shopping Cart</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shoping Cart Section Begin -->
    <section class="shoping-cart spad" id="cart-list">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th class="shoping__product">{{total_cart_items}} Products</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for p_id, item in cart_data.items %}
                                <tr>
                                    <td class="shoping__cart__item">
                                        <img src="{{item.image}}" alt="">
                                        <h5><a href="{% url 'core:product' item.pid %}">{{item.title}}</a></h5>
                                    </td>
                                    <td class="shoping__cart__price">
                                        <span>$</span>{{item.price|floatformat:2}}
                                    </td>
                                    <td class="shoping__cart__quantity">
                                        <!-- <div class="quantity">
                                            <div class="pro-qty">
                                                <input class="product-quantity-{{p_id}}" type="text" value="{{item.quantity}}">
                                            </div>
                                        </div> -->
                                        <input class="product-quantity-{{ p_id }}" type="number" value="{{item.quantity}}">
                                    </td>
                                    <td class="shoping__cart__total">
                                        ${% widthratio item.price 1 item.quantity %}
                                    </td>
                                    <td class="shoping__cart__item__close">
                                        <button class="delete-product" data-product="{{p_id}}" style="border: none;">
                                            <span class="icon_close"></span>
                                        </button>
                                    </td>
                                    <td class="shoping__cart__item__close">
                                        <button class="update-product" data-product="{{p_id}}" style="border: none;">
                                            <span class="icon_close"></span>r
                                        </button>
                                    </td>
                                </tr>
                                {% endfor %}
                              
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__btns">
                        <a href="#" class="primary-btn cart-btn">CONTINUE SHOPPING</a>
                        <a href="#" class="primary-btn cart-btn cart-btn-right"><span class="icon_loading"></span>
                            Upadate Cart</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="shoping__continue">
                        <div class="shoping__discount">
                            <h5>Discount Codes</h5>
                            <form action="#">
                                <input type="text" placeholder="Enter your coupon code">
                                <button type="submit" class="site-btn">APPLY COUPON</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="shoping__checkout">
                        <h5>Cart Total</h5>
                        <ul>
                            <li>Subtotal <span>${{cart_total_amount|floatformat:2}}</span></li>
                            <li>Total <span>${{cart_total_amount|floatformat:2}}</span></li>
                        </ul>
                        {% if total_cart_items %}
                        <a href="{% url 'core:checkout' %}" class="primary-btn">PROCEED TO CHECKOUT</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shoping Cart Section End -->

    {% endblock content %}

templates/core/category_list.html
{% extends 'partials/base.html' %}

{% load static %}

{% block content %}

    <!-- Hero Section Begin -->
    <section class="hero hero-normal">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="hero__categories">
                        <div class="hero__categories__all">
                            <i class="fa fa-bars"></i>
                            <span>All Categories</span>
                        </div>
                        <ul>
                            {% for c in categories %}
                                <li><a href="#">{{c.title}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="hero__search">
                        <div class="hero__search__form">
                            <form action="#">
                                <div class="hero__search__categories">
                                    All Categories
                                    <span class="arrow_carrot-down"></span>
                                </div>
                                <input type="text" placeholder="What do yo u need?">
                                <button type="submit" class="site-btn">SEARCH</button>
                            </form>
                        </div>
                        <div class="hero__search__phone">
                            <div class="hero__search__phone__icon">
                                <i class="fa fa-phone"></i>
                            </div>
                            <div class="hero__search__phone__text">
                                <h5>+65 11.188.888</h5>
                                <span>support 24/7 time</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'img/breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Organi Shop</h2>
                        <div class="breadcrumb__option">
                            <a href="./index.html">Home</a>
                            <span>Shop</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Product Section Begin -->
    <section class="product spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-5">
                    <div class="sidebar">
                        <div class="sidebar__item">
                            <h4>Category</h4>
                            <ul>
                                {% for c in categories %}
                                <li><a href="#">{{c.title}}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9 col-md-7">
                    <div class="filter__item">
                        <div class="row">
                            <div class="col-lg-4 col-md-5">
                                <div class="filter__sort">
                                    <span>Sort By</span>
                                    <select>
                                        <option value="0">Default</option>
                                        <option value="0">Default</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4">
                                <div class="filter__found">
                                    <h6><span>{{categories.count}}</span> Categories found</h6>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-3">
                                <div class="filter__option">
                                    <span class="icon_grid-2x2"></span>
                                    <span class="icon_ul"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        {% for c in categories %}
                        <div class="col-lg-4 col-md-6 col-sm-6">
                            <div class="product__item">
                                <div class="product__item__pic set-bg" data-setbg="{{c.image.url}}">
                                    <ul class="product__item__pic__hover">
                                        <li><a href="#"><i class="fa fa-heart"></i></a></li>
                                        <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                                        <li><a href="#"><i class="fa fa-shopping-cart"></i></a></li>
                                    </ul>
                                </div>
                                <div class="product__item__text">
                                    <h6><a href="{% url 'core:category' c.cid %}">{{c.title}}</a></h6>
                                    <h5>{{c.category.count}} Product{{c.category.count|pluralize}}</h5>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <!-- <div class="product__pagination">
                        <a href="#">1</a>
                        <a href="#">2</a>
                        <a href="#">3</a>
                        <a href="#"><i class="fa fa-long-arrow-right"></i></a>
                    </div> -->
                </div>
            </div>
        </div>
    </section>
    <!-- Product Section End -->

    <!-- Footer Section Begin -->
    {% endblock content %}

templates/core/order_details.html
{% extends 'partials/base.html' %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <p>Hello {{request.user|title}}</p>

    </div>
    <div class="row">
        <h2>Products in this order</h2>
        <a href="{% url 'core:dashboard' %}" class="btn-small d-block"> back </a>
        <br> 
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Order Invoice</th>
                <th>Image</th>
                <th>Title</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total</th>
            </tr>
            </thead>
            <tbody>
            {% for o in order_items %}
            <tr>
                <td>INVOICE_NO-{{o.id}}</td>
                <td>
                    <p><img src="{{o.image}}" style="width: 40px; height: 40px; object-fit: cover;" alt=""></p>
                </td>
                <td>{{o.item|title}}</td>
                <td>{{o.price}}</td>
                <td>{{o.quantity}}</td>
                <td>{{o.total}}</td>
                <!-- <td><a href="{% url 'core:order-details' o.id %}" class="btn-small d-block"> view</a></td> -->
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    </div>
</div>

{% endblock content %}

templates/core/payment-failed.html
<h1>Failed</h1>

templates/core/wishlist.html
{% extends 'partials/base.html' %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <p>Hello {{request.user|title}}</p>

    </div>
    <div class="row">
        <h2>Products in Your Wishlist</h2>
        <a href="{% url 'core:dashboard' %}" class="btn-small d-block"> back </a>
        <br> 
        <table class="table table-hover">
            <thead>
            <tr>
                
                <th>Image</th>
                <th>Title</th>
                <th>Price</th>
                <th>Stock Status</th>
                <th>Action</th>
                <th>Remove</th>
            </tr>
            </thead>
            <tbody>
            {% for w in wishlist %}
            <tr class="pt-30">
                
                <td>
                    <p><img src="{{w.product.image.url}}" style="width: 40px; height: 40px; object-fit: cover;" alt=""></p>
                </td>
                <td>
                    <a href="{% url 'core:product' w.product.pid %}">{{w.product.title|truncatechars:30}}</a>
                </td>
                <td>
                    <h5 class="current-product-price-{{w.product.id}}">${{w.product.price}}</h5>
                </td>
                <td class="text-center">
                    {% if w.product.in_stock %} In Stock {% else %} Out of Stock {% endif %}
                </td>
                <td>
                    <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{w.product.id}}" >
                    <input type="hidden" class="product-pid-{{w.product.id}}" value="{{w.product.pid}}">
                    <input type="hidden" class="product-image-{{w.product.id}}" value="{{w.product.image.url}}">
                    <input type="hidden" class="product-id-{{w.product.id}}" value="{{w.product.id}}">
                    <input type="hidden" class="product-title-{{w.product.id}}" value="{{w.product.title}}">
                    <button class="btn btn-success btn-small add-to-cart-btn" data-index="{{w.product.id}}">
                        Add to cart
                    </button>
                </td>
                <td>
                    <a href="" ">Remove</a>
                </td>
                
                
            </tr>
            {% empty %}
            <tr>
                <td><p>Nothing wishlist yet...</p></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    </div>
</div>

{% endblock content %}