core/urls.py
from django.urls import path, include

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name="index"),
    #! product
    path('products', views.product_list_view, name="products"),
    path('product/<pid>', views.product_details_view, name="product"),


    #! category
    path('categories', views.category_list_view, name="categories"),
    path('category/<cid>', views.category_product_list_view, name="category"),

    #! vendor
    path('vendors', views.vendors_list_view, name="vendors"),
    path('vendor/<vid>', views.vendor_details_view, name="vendor"),

    #! tags
    path('products/tags/<slug:tag_slug>', views.tag_list_view, name="tags"),

    #! add reviews
    path('reviews/<pid>', views.review_form_view, name="reviews"),

    #! Search by product title
    path('search/', views.search_products_view, name="search_products"),

    #! filter products by category, vendor
    path('filter_products/', views.filter_products_view, name="filter_products"),

    #! add product to cart
    path('add_to_cart', views.add_to_cart, name="add_to_cart"),

    #! cart page
    path('cart', views.cart_view, name="cart"),

    #! delete-item-from-cart
    path('delete-from-cart', views.delete_item_from_cart, name="delete-from-cart"),

    #! update cart
    path('update-cart', views.update_cart, name="update-cart"),

    #! Checkout url
    path('checkout', views.checkout_view, name="checkout"),

    #! paypal url
    path('paypal/', include('paypal.standard.ipn.urls')),

    #! payment completed url
    path('payment-completed', views.payment_completed_view, name="payment-completed"),

    #! payment failed url
    path('payment-failed', views.payment_failed_view, name="payment-failed"),

     #! dashboard url
    path('dashboard/', views.dashboard_view, name="dashboard"),

     #! order details url
    path('dashboard/order/<int:id>', views.order_detail_view, name="order-details"),

    #! making address default url
    path('make-default-address', views.make_address_default_view, name="make-default-address"),

    #! adding to wishlist url
    path('add-to-wishlist', views.add_to_wishlist_view, name="add-to-wishlist"),

    #! wishlist view url
    path('wishlist', views.wishlist_view, name="wishlist"),

    #! removing from wishlist view url
    path('remove-from-wishlist', views.remove_from_wishlist, name="remove-from-wishlist"),

    #! contact view url
    path('contact', views.contact_view, name="contact"),

    #! ajax contact view url
    path('ajax-contact-form', views.ajax_contact, name="ajax-contact-form"),

]

lexy/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userAuth.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    

    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userAuth/urls.py
from django.urls import path
from . import views

app_name = 'userAuth'

urlpatterns = [
    path('register', views.register_view, name='register'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('user-settings', views.user_settings_view, name='user-settings'),
]

userAuth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.TextField(null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.username
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) #! one user per profile
    image = models.ImageField(upload_to="image")
    full_name = models.CharField(max_length=200, null=True, blank=True)
    bio = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    verified = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.full_name
    
class ContactUs(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    class Meta:
        verbose_name = "Contact Us"
        verbose_name_plural = "Contact Us"

    def __str__(self) -> str:
        return self.full_name

userAuth/forms.py
from django import forms
from django.forms.widgets import PasswordInput, EmailInput

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


from . models import User

class MyUserCreationForm(UserCreationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(AuthenticationForm):

    email = forms.EmailField(widget=EmailInput())
    password = forms.CharField(widget=PasswordInput())

userAuth/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages #! for flash messages

from . forms import MyUserCreationForm, LoginForm

from . models import User, Profile

# Create your views here.

def register_view(request):

    form = MyUserCreationForm()

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f"Hey {username} your account was created successfully")
            new_user = authenticate(username=form.cleaned_data['email'], password=form.cleaned_data['password1'])

            login(request, new_user)
            return redirect('core:index')
        else:
            messages.error(request, 'An error occurred during Registration')

    context = {'form': form}
    return render(request, 'userAuth/register.html', context)   


def login_view(request):

    if request.user.is_authenticated:
        messages.success(request, 'You are already logged in :)')
        return redirect('core:index')


    if request.method == 'POST':

        # form = LoginForm(request.POST)
    
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email=email)
        except:
            messages.error(request,'User does not exist')

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('core:index')
        else:
            messages.error(request,'username or password is incorrect')
    
    context = {}
    return render(request, 'userAuth/login.html', context)


def user_settings_view(request):

    profile = Profile.objects.get(user=request.user)

    context = {
        'profile': profile
    }
    return render(request, 'userAuth/settings.html', context)


def logout_view(request):

    logout(request)

    messages.success(request, "Logout success")

    return redirect('userAuth:login')

    

templates/userAuth/login.html
{% extends 'partials/base.html' %}

<!-- {% load crispy_forms_tags %} -->

{% block content %}

<body>
        

    <div class="container bg-light shadow-md p-5 form-layout">

        <h3>Login to your Account</h3>

        <hr>
        <br>
        <!-- {% if form.Errors %}
            <div class="alert alert-danger">
                <strong>{{form.errors}}</strong>
            </div>
        {% endif %} -->

        <form action="" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
              </div>
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>

            <!-- <button class="btn btn-primary w-100 btn-block p-2" type="submit">
                Login &nbsp; <i class="fa fa-sign-in" aria-hidden="true"></i>
            </button> -->

        </form>

        <br>

        <div class="text-center">
            <p>Don't have an account? </p> <a href="{% url 'userAuth:register' %}">Register</a>
        </div>

    </div>
    <br>
</body>

{% endblock %}

templates/userAuth/register.html
{% extends 'partials/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <body>
        

        <div class="container bg-light shadow-md p-5 form-layout">

            <h3>Create your Account</h3>

            <h5>Start Selling your products!</h5>

            <hr>
            <br>
            {% if form.Errors %}
            <div class="alert alert-danger">
                <strong>{{form.errors}}</strong>
            </div>
            {% endif %}

            <form action="" method="post" autocomplete="off">
                {% csrf_token %}
                {{form.username|as_crispy_field}}
                <br>
                {{form.email|as_crispy_field}}
                <br>
                {{form.password1|as_crispy_field}}
                <br>
                {{form.password2|as_crispy_field}}
                <br>

                <button class="btn btn-primary w-100 btn-block p-2" type="submit">
                    Create Account &nbsp; <i class="fa fa-sign-in" aria-hidden="true"></i>
                </button>

            </form>

            <br>

            <div class="text-center">
                <p>Already have an account? </p> <a href="{% url 'userAuth:login' %}">Login</a>
            </div>

        </div>
        <br>
    </body>
{% endblock content %}

templates/userAuth/settings.html
{% extends 'partials/base.html' %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <div class="card mb-5 mb-lg-0">
            <div>
                <form class="mb-4" method="post">{% csrf_token %}
                    
                    <div class="card-header text-center">
                        <h5>Your profile {{profile.full_name|title}}</h5>
                    </div>
                    <div class="container " style="align-self: center;">
                        <div class="form-group col-md-6">
                            <input class="form-control" name="full_name" value="{{profile.full_name|title}}" type="text">
                        </div>
                        <div class="form-group col-md-6">
                            <input class="form-control" name="bio" value="{{profile.bio}}" type="text">
                        </div>
                        <div class="form-group col-md-6">
                            <input class="form-control" name="phone" value="{{profile.phone}}" type="text">
                        </div>
                        <div class="form-group col-md-6">
                            <input class="form-control" name="mobile" value="{{profile.verified}}" type="text">
                        </div>
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-success font-weight-bold">Save Address</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}